### ISSUE TITLE
Auth service showing "APPLICATION FAILED TO START"

### ISSUE THREAD

**Issue by devratnaarya** [keets2012/microservice-integration#2]
APPLICATION FAILED TO START

Description:

Field mapper com.blueskykong.auth.dao.impl.MybatisClientSecretDAO required a bean of type 'com.blueskykong.auth.dao.mapper.ClientSecretMapper' that could not be found.

Action:

Consider defining a bean of type 'com.blueskykong.auth.dao.mapper.ClientSecretMapper' in your configuration.

**Comment by CANGWU** [comment]
How did you start the application? Did you start it through the eclipse or others which would compile the classes in different directory structures. Maybe you can find the correct class path of the mapper and fix the config in com.blueskykong.auth.config.DatasourceConfig. The MapperBean of this project is produced by SqlSessionFactory. Hope this can help you.
