### ISSUE TITLE
Error starting ApplicationContext.

### ISSUE THREAD

**Issue by skywp** [keets2012/microservice-integration#3]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-09-28 15:09:54.388 ERROR 16388 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'httpHandler' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/HttpHandlerAutoConfiguration$AnnotationConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.server.reactive.HttpHandler]: Factory method 'httpHandler' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webHandler' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration$EnableWebFluxConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'routePredicateHandlerMapping' defined in class path resource [org/springframework/cloud/gateway/config/GatewayAutoConfiguration.class]: Unsatisfied dependency expressed through method 'routePredicateHandlerMapping' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'filteringWebHandler' defined in class path resource [org/springframework/cloud/gateway/config/GatewayAutoConfiguration.class]: Unsatisfied dependency expressed through method 'filteringWebHandler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'throttleGatewayFilterFactory' defined in class path resource [com/blueskykong/gateway/enhanced/config/ServiceConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.blueskykong.gateway.enhanced.filter.ThrottleGatewayFilterFactory]: Factory method 'throttleGatewayFilterFactory' threw exception; nested exception is com.blueskykong.gateway.enhanced.exception.ServerException: PROPERTY_NOT_INITIAL

How to start the module of gateway-enhanced?I have been runned "mvn clean install".

**Comment by keets2012** [comment]
根据报错，你的配置有问题，请检查如下配置是否正常：

```yml
gateway:
  limit:
    redis-rate: # token
      replenish-rate: 10
      burst-capacity: 3000
    throttle: # leaky
      capacity: 10000
      refill-tokens: 50
      refill-period: 5
```
