### ISSUE TITLE
maven依赖报错

### ISSUE THREAD

**Issue by wlb632363** [keets2012/microservice-integration#7]
spring-cloud-oauth2 maven依赖报错，OAuth2Config文件无法引入AuthorizationServerConfigurerAdapter

**Comment by CANGWU** [comment]
请问有mvn clean install过吗，可以尝试reimport依赖

**Comment by wlb632363** [comment]
> 请问有mvn clean install过吗，可以尝试reimport依赖

重新clean install 后报错
Failed to execute goal on project auth-server: Could not resolve dependencies for project org.springframework.boot:auth-server:jar:2.1.3.RELEASE: Failure to find org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:jar:2.1.0.M4 in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced -> [Help 1]

**Comment by wlb632363** [comment]
下载不了org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:jar:2.1.0.M4这个依赖

**Comment by CANGWU** [comment]
估计是本地的maven库没有下载完整导致的问题，可以尝试将本地的相关依赖删除掉再重新mvn clean install

**Comment by wlb632363** [comment]
> 估计是本地的maven库没有下载完整导致的问题，可以尝试将本地的相关依赖删除掉再重新mvn clean install

已经重新clean install过了 ，但是还是报错 Failure to find org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:jar:2.1.0.M4，就是这个包一直下载不了

**Comment by keets2012** [comment]
应该是网络问题。先关闭issue。

**Comment by sunshinexb** [comment]
https://repo.maven.apache.org/maven2/org/springframework/security/oauth/boot/spring-security-oauth2-autoconfigure/2.1.0.M4/spring-security-oauth2-autoconfigure-2.1.0.M4.jar

这个包在仓库中好像不在了  404

**Comment by sunshinexb** [comment]
![image](https://user-images.githubusercontent.com/12893868/55647805-321d9a80-5811-11e9-9247-8a55b9a3595d.png)
