### ISSUE TITLE
关于网关auth

### ISSUE THREAD

**Issue by VergLsm** [keets2012/microservice-integration#9]
看了一下这个项目的技术选型，都是很好的
唯一有个不明白的地方，为什么不用JWT？
按照框架图来看，是不是用户每次请求，不管登录与否，都会调用到auth系统？
如果是这样，那会不会造成auth系统负载过高？成为整个系统的瓶颈？

**Comment by keets2012** [comment]
1. 用了JWT
2. auth作为基础服务，多实例部署，可以应对调用。

**Comment by VergLsm** [comment]
@keets2012 再请教一下，为什么使用了JWT还需要访问auth呢？能不能把用户信息加密存到JWT里，定时过期，这样只需要确保JWT有效，就不需要频繁调用auth验证。

**Comment by CANGWU** [comment]
主要是为了解决一个需求，不允许单客户端多点登录，同一时间内只能有一个Token有效。如果只使用JWT，生成的Token会在失效时间前都有效，无法简单地失效这样一个Token。举个例子，一个JWT内设定的失效时间为24小时，那么24小时内这个Token都是有效的，此时客户端可以申请一个新的Token，在失效时间前，两个Token都会有效。
